# Site settings
email: "beomjun615@naver.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: HunetDBA
description: Hunet Databased Innovation Team Github blog test page
url: "https://hunetdba.github.io/"
twitter_username:
default_img: https://picsum.photos/2000/1200?image=0

# Profile settings
name: Hunet
profile_img: https://imagizer.imageshack.com/v2/1600x1200q90/922/W8sS7m.png
profile: "Hunet Databased Innovation Team 기술 블로그 테스트"
social: social test
github: "https://github.com/Hunetdba/hunetdba.github.io"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
