# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: HunetDBA
description: Hunet Databased Innovation Team Github blog test page
url: "https://hunetdba.github.io/"
twitter_username:
default_img: https://picsum.photos/2000/1200?image=0

# Profile settings
name: Hunet
profile_img: ./_image/hunetblogbanner.png
profile: Hunet Databased Innovation Team
social:
github: "https://github.com/Hunetdba/hunetdba.github.io"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
